### PR TITLE
alternate row colors for tables

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Tracking lines in the table is challenging because all the data is oneliner. The PR makes the table header sticky, and colors alternate rows for easy reading.

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
The last commit is an unrelated fix. `news://gnu.emacs.help` is [a valid URL](https://www.emacswiki.org/emacs/EmacsNewsgroups).

**Review by Josh-Cena — APPROVED** [review]
Thanks Onkar!

Since you are one of the other actively using this dashboard, just want to ask do you find the docs helpful at all? Or are you just focusing on a few of these warnings?

**Comment by OnkarRuikar** [comment]
Some of the things in the doc are not clear, e.g. 
> ### Image link
> This rule reports internal image links (ending in one of the image extensions). It’s generally a bad idea to provide links to them rather than directly displaying them and could be a typo. You don’t need to wrap images in another <a>.

So in the "image link" section, I don't understand what's wrong with `/en-US/docs/Learn/Forms/Styling_web_forms/background.jpg.` The docs need to mention, in some cases, how to fix the issues as well.

I am fixing some of the issues willy-nilly in my free time. Let me know if you are already working on these.

**Comment by Josh-Cena** [comment]
It reports `<a>` whose `href` points to an image and recommends using ``, because you don't need to explicitly point people to open an image in a new tab.

If you don't see a PR from me then I'm not working on it. I usually send a PR within 20 min after I start.

**Comment by OnkarRuikar** [comment]
People don't know how to use markdown style image embedding in tables, so they've used [anchor tags to embed images in tables](https://github.com/mdn/content/blob/dfe56b2122cd389a3a628c6e75c2be7378ccc07a/files/en-us/web/media/formats/video_codecs/index.md?plain=1#L309). To keep the table code readable I think we need to let such warnings slide.

**Comment by Josh-Cena** [comment]
No that's not the issue. Markdown and HTML don't make a difference in my checker. The problem is you don't need to wrap the image in another anchor tag. If you want to let people open it in a new tab, they can already do so by right clicking.

**Pull request merged**
